/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Ciudadano;

/**
 *
 * @author 10 Spring Creators
 */
public class LoginAdminJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginAdminJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeAdmin = new javax.swing.JLabel();
        JlabelUser = new javax.swing.JLabel();
        JlaberlPass = new javax.swing.JLabel();
        JTextFielduser = new javax.swing.JTextField();
        JButtonEntrar = new javax.swing.JButton();
        JPasswordFieldpass = new javax.swing.JPasswordField();
        JlabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeAdmin.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabeAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabeAdmin.setText("ADMIN");
        getContentPane().add(jLabeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        JlabelUser.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        JlabelUser.setForeground(new java.awt.Color(255, 255, 255));
        JlabelUser.setText("Usuario:");
        getContentPane().add(JlabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 100, -1));

        JlaberlPass.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        JlaberlPass.setForeground(new java.awt.Color(255, 255, 255));
        JlaberlPass.setText("Contraseña:");
        getContentPane().add(JlaberlPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, 30));

        JTextFielduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFielduserActionPerformed(evt);
            }
        });
        getContentPane().add(JTextFielduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 240, 30));

        JButtonEntrar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        JButtonEntrar.setForeground(new java.awt.Color(219, 151, 103));
        JButtonEntrar.setText("Entrar");
        JButtonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JButtonEntrarMouseEntered(evt);
            }
        });
        getContentPane().add(JButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 130, 40));
        getContentPane().add(JPasswordFieldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 240, 30));

        JlabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ffondo.png"))); // NOI18N
        JlabelFondo.setMaximumSize(new java.awt.Dimension(300, 500));
        JlabelFondo.setMinimumSize(new java.awt.Dimension(150, 250));
        JlabelFondo.setPreferredSize(new java.awt.Dimension(300, 500));
        getContentPane().add(JlabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextFielduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFielduserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFielduserActionPerformed

    private void JButtonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonEntrarMouseClicked
        String Usuario="admin";
        String Contraseña="123abc";
        
                     
        String Pass=new String(JPasswordFieldpass.getPassword());
        
        if(JTextFielduser.getText().equals(Usuario)&& Pass.equals(Contraseña)){           
                      
            MenuAdminJFrame mp=new MenuAdminJFrame();
            mp.setVisible(true);
            dispose();         
        }
            else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
        }
            
        

        
        
        
    }//GEN-LAST:event_JButtonEntrarMouseClicked

    private void JButtonEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonEntrarMouseEntered
        
    }//GEN-LAST:event_JButtonEntrarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdminJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonEntrar;
    private javax.swing.JPasswordField JPasswordFieldpass;
    private javax.swing.JTextField JTextFielduser;
    private javax.swing.JLabel JlabelFondo;
    private javax.swing.JLabel JlabelUser;
    private javax.swing.JLabel JlaberlPass;
    private javax.swing.JLabel jLabeAdmin;
    // End of variables declaration//GEN-END:variables
}
